name: CI
on:
  push: { branches: ["main"] }
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8 pytest
      - name: Lint & Test
        run: |
          python -m black --check scripts tests
          python -m isort --check-only scripts tests
          pytest -q
      - name: Toy heuristics check
        run: |
          python scripts/heuristics.py data/toy_bio_eval.jsonl

