name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Create venv and install deps
        run: |
          uv venv .venv --python 3.10
          uv pip install --python .venv -r requirements.txt
      - name: Lint
        run: |
          .venv/bin/ruff version
          .venv/bin/ruff check robustcbrn tests
      - name: Tests
        run: |
          .venv/bin/pytest -q
      - name: Validate release artifacts
        run: |
          bash scripts/validate_release.sh
